POST http://localhost:8080/workouts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjgiLCJpYXQiOjE3NjAxODExNTAsImV4cCI6MTc2MDE4NDc1MH0.nbDB0Moysp4IlX3RfdS9yC8fFrDk815pDffTQ-hWjto


{
  "name": "W1D1"
}